### ISSUE TITLE
neighbors support?

### ISSUE THREAD

**Issue by RReverser** [jbuckmccready/static_aabb2d_index#1]
Is it possible to port the `neighbors` method from flatbush? As far as I understand, it's currently not ported / not exposed via the API. /cc @mourner

**Comment by jbuckmccready** [comment]
It is definitely possible, just not yet implemented, I think it could be easily ported using the [std::collections::binary_heap](https://doc.rust-lang.org/std/collections/binary_heap/index.html) as the priority queue. I'll look at it sometime today.

**Comment by RReverser** [comment]
Ah awesome, thanks!

**Comment by RReverser** [comment]
Actually... I've realised that what I probably need instead is KD-tree as I'm working with point data, so I can keep the issue open but this is not very urgent.

**Comment by jbuckmccready** [comment]
Ah yeah, you can use this spatial index for point data as well (by having `min_x == max_x` and `min_y == max_y` for all items added) but it is a little bit less efficient in memory and comparisons (but may still be plenty fast for your use case). The algorithm used can definitely be applied to points efficiently, there is actually an issue in the flatbush library about it: https://github.com/mourner/flatbush/issues/33.

In Rust it would likely be a different type for performance and Rust's static type system, I don't have a use for that now but maybe I'll add that to this library sometime in the future as well.

I committed changes to support nearest neighbor queries (commit: https://github.com/jbuckmccready/static_aabb2d_index/commit/f2ea39f1cefb1bed5354c9341b2bf37ec1a86457), the unit tests pass but I haven't done any benchmarking, optimizations, or manual graphical confirmation tests yet.

**Comment by RReverser** [comment]
> The algorithm used can definitely be applied to points efficiently, there is actually an issue in the flatbush library about it: [mourner/flatbush#33](https://github.com/mourner/flatbush/issues/33).

Ah yes, I've posted that comment above after chatting with mourner - he said the changes to represent points are a bit tricky, so for now I've looked at KD-tree implementations and stopped on https://docs.rs/kd-tree which seems promising and works well.

> I committed changes to support nearest neighbor queries (commit: [f2ea39f](https://github.com/jbuckmccready/static_aabb2d_index/commit/f2ea39f1cefb1bed5354c9341b2bf37ec1a86457)), the unit tests pass but I haven't done any benchmarking, optimizations, or manual graphical confirmation tests yet.

Awesome, thanks. I'll close this issue for now then.
